version: '2'

services:
  athena:
    image: athena.api
    build:
      context: ./Athena.Api
      dockerfile: Dockerfile
    depends_on:
      - consul
  consul:
    image: consul
    command: "join consul-server"
networks:
  default:
    external:
      name: def_net